version: "3.1"

services:
  app:
    image: habrrssparser
    depends_on:
      - db
    restart: 'always'
    build: ./app
    volumes:
      - './app/logs:/app/logs'
  db:
    image: habrrssparser_db
    restart: 'unless-stopped'
    build: ./db
    environment:
      POSTGRES_PASSWORD: "$DB_PASSWORD"
      POSTGRES_USER: "$DB_USER"
      POSTGRES_DB: "$DATABASE"
    ports:
      - '5432:5432'
    volumes:
      - './db/data:/var/lib/postgresql/data'